/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CascadeSelect: typeof import('primevue/cascadeselect')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    LastNGamesChart: typeof import('./src/components/LastNGamesChart.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MyLogo: typeof import('./src/components/MyLogo.vue')['default']
    MyPlayerSearch: typeof import('./src/components/MyPlayerSearch.vue')['default']
    PastStatHitsChart: typeof import('./src/components/PastStatHitsChart.vue')['default']
    PredictionsChart: typeof import('./src/components/PredictionsChart.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    PropCards: typeof import('./src/components/PropCards.vue')['default']
    PropDisplayPanel: typeof import('./src/components/PropDisplayPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SameGamePropsChart: typeof import('./src/components/SameGamePropsChart.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
  }
}
